### PR TITLE
Create cauliflowersoup.md

### PR DESCRIPTION
**Pull request by liiaang**
yo this soup is the bomb dotcom

### CODE REVIEW

**Comment by jragins** [comment]
Um how do I make this without a vitamix?

**Comment by liiaang** [comment]
@jragins  problem solved! :+1:

**Comment by jragins** [comment]
Please send coupon asap

**Comment by liiaang** [comment]
will send as soon as you give me a :+1: @jragins

**Comment by jragins** [comment]
No, coupon first, then thumbs up

**Comment by jragins** [comment]
:+1:

**Comment by liiaang** [comment]
bed-bath-and-beyond-20-off-coupon

**Comment by jragins** [comment]
:-1:

**Comment by jragins** [comment]
expired

**Pull request merged**
